version: "3.9"
services:
  php:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: php:8.0-apache
    extra_hosts:
      - "luglockers.loc:127.0.0.1"
    hostname: luglockers.loc
    domainname: loc
    container_name: luglockers-apache
    ports:dispatch
      - 85:80
    volumes:
      - ./:/var/www/luglockers
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: luglockers-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=luglockers
      - MYSQL_PASSWORD=password
    ports:
      - 3311:3306

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    links:
#      - database:mysql
#    ports:
#      - 8181:80
#    environment:
#      PMA_HOST: mysql
#      MYSQL_USER: root
#      MYSQL_ROOT_PASSWORD: password
